name: CI - Single Dependabot PR

on:
  schedule:
    # At 7:30 every Wednesday (6:30 UTC)
    - cron: "30 6 * * 3"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_update_dependencies.yml@v2.9.0
    if: github.repository_owner == 'sintef'
    with:
      git_username: DLite Developers
      git_email: "Team4.0@SINTEF.no"
      permanent_dependencies_branch: ci/dependabot-updates
      default_repo_branch: master
      pr_labels: "CI/CD"
      extra_to_dos: "- [ ] Make sure that the PR is **squash** merged, with a sensible commit message."
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
